### ISSUE TITLE
Remove every Firebase configuration from the codebase

### ISSUE THREAD

**Issue by gregito** [BenTrk/kisgeri24#30]
It is the biggest security concern of the app right now since all the URLs and API keys are present in the codebase.

Ideally, these values should never appear anywhere in the codebase, just their reference (providing them from a configuration at compile time or from an environment variable - also given at compile time - ).

First of all, **these values have to be removed completely**, and **revoke/renew all the API keys** (since they are present in the git history).

**Comment by OnionKiller** [comment]
I'm not sure, if it's actually wrong.
I was looking ito this earlier, and it seems, that the config was done in an ok way. (Based on [this SO question](https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public), because I'm not a firebase expert, nor have real experience.)
So I would modify this issue to reviewing the firebase configuration from a security standpoint.
